name: Netflix API CI

on: [push]
jobs:
  run-tests:
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3
      - name: Install Requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-django
      - name: Run migrations
        run: python manage.py migrate
      - name: Run Tests
        run: py.test